import Mathlib.Topology.Homotopy.Path
import Mathlib.Topology.Bases
open Set

variable {X : Type _} [TopologicalSpace X] (x₀ : X) {x₁ : X }
-- def baseSet : TopologicalSpace X 

#check X

def coverSet :=
  Σ x₁ : X , Path.Homotopic.Quotient x₀ x₁

#check coverSet
#synth TopologicalSpace (Path x₀ x₁)

--example : IsOpen (univ : Cover) := 
 -- isOpen_univ

open TopologicalSpace

example (X : Type _) (s : Set (Set X)) (h : ∀ U V : Set X, U ∈ s → V ⊆ U → V ∈ s)
  (h' : ∀ x: X, ∃ U ∈ s, x ∈ U) :
    IsTopologicalBasis (t := generateFrom s) s := by
  let _ := generateFrom s
  apply isTopologicalBasis_of_open_of_nhds
  · intros u hu
    exact isOpen_generateFrom_of_mem hu
  · intros x U hx hU
    induction hU with
    | basic V hV => use V, hV, hx
    | univ => simpa using h' x
    | inter V W _ _ h₃ h₄ =>
        rcases h₃ hx.1 with ⟨R, _, hxR, hRV⟩
        rcases h₄ hx.2 with ⟨S, S_in, hxS, hSW⟩
        refine ⟨R ∩ S, ?_, ⟨hxR, hxS⟩, ?_⟩
        · exact h _ _ S_in (Set.inter_subset_right R S)
        · exact Set.inter_subset_inter hRV hSW
    | sUnion S _ hS =>
        rcases hx with ⟨T, T_in, hxT⟩
        rcases hS T T_in hxT with ⟨V, V_in, hxV, hVT⟩
        use V, V_in, hxV
        exact Set.subset_sUnion_of_subset S T hVT T_in



-- TODO:

-- 1. Construct the path space equipped with the compact open topology
-- 2. Take the quotient of the path space with respect to the equivalence relation generated by 
--    homotopy equivalence relative to boundary.
-- 3. Show that the basis Hatcher gives is a basis for the quotient of the compact open topology.
-- 4. Use Hatcher's characterization to prove that the topological space we get is simply connected and 
--    a covering space of the base space X.
-- 5. Profit?


-- Hybrid approach

-- Construct Hatcher's version of the universal cover
-- Then show that the topology it has is equivalent to the one described in Bourbaki 
-- by taking the quotient of the path space of X (equipped with the compact open topology) 
-- with repsect to homotopy equivalence rel boundary.

-- I.e.  need to show that Hatcher's basis generates the compact-open topology quotient.

-- 










#exit


Sigma 